### ISSUE TITLE
Error trying to use ifc2json.py

### ISSUE THREAD

**Issue by wkrt** [IFCJSON-Team/IFC.JSON-4#13]
I followed the instructions at /file_converters for Conda and tried to convert an IFC file to JSON.
This is the result: 
`ModuleNotFoundError: No module named 'ifcjson'`
Any suggestions what went wrong?

**Comment by janbrouwer** [comment]
Ah I see that there is no reference that you also need to download all the files from /file_converters from this repository, the folder ['ifcjson' module folder](https://github.com/buildingSMART/ifcJSON/tree/master/file_converters/ifcjson ) should be present as well.
Maybe you only downloaded the single file? I will update the documentation..

**Comment by wkrt** [comment]
Thanks a lot, that solved my problem!
Installation documentation is also more understandable now.
