### ISSUE TITLE
ifc-prefix

### ISSUE THREAD

**Issue by janbrouwer** [IFCJSON-Team/IFC.JSON-4#2]
https://github.com/IFCJSON-Team/IFC.JSON-4/tree/master/Documentation#23-ifc-prefix
shouldn't we just leave this paragraph out completely because the reference here is IFC4 instead of IFC.JSON-5Alpha?

**Comment by pipauwel** [comment]
Yes, sounds good.

**Comment by janbrouwer** [comment]
Decided: paragraph will be removed for IFC4
