### ISSUE TITLE
change "class" for something closer to IFC

### ISSUE THREAD

**Issue by janbrouwer** [IFCJSON-Team/IFC.JSON-4#3]
We for now describe the ifc entity type of an object as:
- "Class": "IfcWall"

This is ok, but maybe something else would be more IFC like?
- "entity": "IfcWall" (from STEP schema)
- "ifcType": "IfcWall" ([from EIR](https://github.com/buildingSMART/IDS/blob/master/examples/project%20and%20site%20properties/project_and_site_EIR.txt), although type seems more like basic types like LIST, BOOL etc.)

Or to align with [geojson](https://geojson.org/)?
- "feature": "IfcWall"

Or from [cityJSON](https://www.cityjson.org/about/)(would that work with JSON-SCHEMA?)
- "type": "IfcWall"

**Comment by pipauwel** [comment]
I would like to avoid to introduce again the relatively awkward distinction between Types and Entities in JSON, if possible. As far as I am concerned, "type": "IfcWall" seems to be the better option.

**Comment by janbrouwer** [comment]
Decision: "type"
