### ISSUE TITLE
Args inverse

### ISSUE THREAD

**Issue by bbrangeo** [IFCJSON-Team/IFC.JSON-4#8]
https://github.com/buildingSMART/ifcJSON/blob/7ead4a168a757fca1922584e127a70cf8364b864/file_converters/ifc2json.py#L44

Traceback (most recent call last):
  File "ifc2json.py", line 80, in <module>
    NO_INVERSE=args.inverse,
AttributeError: 'Namespace' object has no attribute 'inverse'

Change line 80 : inverse to no_inverse

**Comment by Samiya150** [comment]
still gives error : line 80, in <module>
    NO_INVERSE=args.inverse,
AttributeError: 'Namespace' object has no attribute 'inverse'

**Comment by janbrouwer** [comment]
Thanks for reporting this should be fixed now
